#created on: 24/09/2009
package example.simple

import example.simple.Simple;

rule "Meio"
	when
		$s : Simple(input > 10 && input <= 20)
	then 
		$s.setOutput(true);
end

rule "Inicio e Fim"
	when
		$s : Simple(input <= 10)
	then 
		$s.setOutput(false);
end

rule "Conflitante"
	when
		$s : Simple(input > 10)
	then 
		$s.setOutput(true);
end

rule "Fim"
	when
		$s : Simple(input > 20)
	then 
		$s.setOutput(false);
end